# Generated by Django 6.0.3 on 2026-04-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
