# Generated by Django 6.0.3 on 2026-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='SemNome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default='O', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='SemSobrenome', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
