# Generated by Django 6.0.3 on 2026-04-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_email_client_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
