# Generated by Django 6.0.3 on 2026-05-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_monthly_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_whatsapp_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
